captainVersion: 4
services:
  $$cap_appname:
    build: .
    restart: always
    ports:
      - $$cap_rdp_port:3389
    environment:
      RDP_PORT: $$cap_rdp_port
    caproverExtra:
      notExposeAsWebApp: "true"
      dockerfileLines:
        - FROM kalilinux/kali-rolling
        - RUN apt-get update && apt-get install -y kali-linux-default
          kali-desktop-xfce xrdp
        - RUN apt update && apt -y install kali-linux-large
        - RUN echo "xfce4-session" > /etc/skel/.xsession
        - RUN service xrdp start
        - EXPOSE 3389
        - CMD ["service", "xrdp", "start", "&&", "tail", "-f",
          "/var/log/xrdp.log"]
caproverOneClickApp:
  variables:
    - id: $$cap_rdp_port
      label: RDP Port
      defaultValue: 3389
  instructions:
    start: This will deploy a Kali Linux container with GUI and remote desktop
      support.
    end: Kali Linux is deployed and accessible via R
