captainVersion: 4
services:
    $$cap_appname:
        image: registry:2
        restart: always
        ports:
            - '$$cap_registry_port:5000'
        volumes:
            - $$cap_appname-data:/data
            - $$cap_appname-auth:/auth
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
            HTPASSWD_USER: $$cap_htpasswd_user
            HTPASSWD_PASSWORD: $$cap_htpasswd_password
        caproverExtra:
            containerHttpPort: 5000
caproverOneClickApp:
    variables:
        - id: $$cap_registry_port
          label: Registry Port
          description: Enter the desired host port for the Docker Container Registry (default: 5000).
          defaultValue: 5000
        - id: $$cap_htpasswd_user
          label: Registry Username
          description: Enter the desired username for the registry authentication.
          defaultValue: registryuser
        - id: $$cap_htpasswd_password
          label: Registry Password
          description: Enter the desired password for the registry authentication.
          defaultValue: registrypassword
    instructions:
        start: Based on https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-18-04
        end: Docker Container Registry is set up and running.
    displayName: Docker Container Registry
    isOfficial: false
    description: A private Docker Container Registry.
